# Generated by Django 3.0.3 on 2020-04-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25)),
                ('college_name', models.CharField(max_length=50)),
                ('captain_name', models.CharField(max_length=25)),
                ('college_address', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=25)),
                ('team_logo', models.ImageField(upload_to='media/image')),
                ('group', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='team_register',
        ),
    ]
