# Generated by Django 3.0.3 on 2020-04-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0002_auto_20200408_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='team',
            new_name='team_register',
        ),
    ]
