# Generated by Django 3.0.3 on 2020-04-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0003_auto_20200408_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='fname',
        ),
    ]
