# Generated by Django 3.0.3 on 2020-04-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0004_auto_20200422_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='mobile_no',
            new_name='phone',
        ),
    ]
