# Generated by Django 3.0.3 on 2020-04-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0005_auto_20200422_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_register',
            old_name='player_email',
            new_name='pemail',
        ),
        migrations.RenameField(
            model_name='player_register',
            old_name='player_name',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='player_register',
            old_name='player_no',
            new_name='pnumber',
        ),
    ]
