# Generated by Django 3.0.3 on 2020-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0006_auto_20200422_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('launching_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='sport_product',
        ),
        migrations.AlterField(
            model_name='player_register',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='team_register',
            name='date',
            field=models.DateField(),
        ),
    ]
