# Generated by Django 3.0.3 on 2020-04-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0007_auto_20200422_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='a_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='State',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='group1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mobile_no',
            new_name='number1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='number2',
        ),
    ]
