# Generated by Django 3.0.3 on 2020-04-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0008_auto_20200424_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='a_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='number1',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='number2',
            new_name='zip_code',
        ),
    ]
