# Generated by Django 3.0.3 on 2020-04-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0009_auto_20200424_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_register',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team_register',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
