# Generated by Django 3.0.3 on 2020-05-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0010_auto_20200424_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='group',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mobile_no',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='group1',
            new_name='state',
        ),
    ]
