# Generated by Django 3.0.3 on 2020-06-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0011_auto_20200513_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_register',
            name='group',
        ),
    ]
