# Generated by Django 3.0.3 on 2020-06-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0012_remove_team_register_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='team_register',
            name='college_address',
            field=models.CharField(max_length=100),
        ),
    ]
