# Generated by Django 3.0.3 on 2020-06-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0014_auto_20200604_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registaration',
        ),
    ]
