# Generated by Django 3.0.3 on 2020-06-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0021_auto_20200612_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_register',
            name='team_logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
