# Generated by Django 3.0.3 on 2020-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crikartapp', '0025_auto_20200720_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_register',
            name='team_logo',
            field=models.ImageField(default='', upload_to='media/upload/'),
        ),
    ]
